### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by jacksocu** [Summy99/IBM_Model_Magic#9]
If you go full screen while in a level you will the full screen will go past your screen

1. Make sure your not zoomed in
2. start menu
3. settings
4. zoom in 
5. done

**Comment by Summy99** [comment]
Can't reproduce, might be an issue specific to user's screen

**Comment by Summy99** [comment]
Further investigation: only seems to happen on smaller screens, resolution gets set incorrectly

**Comment by Summy99** [comment]
Fixed, obsolete code set resolution when it shouldn't
